<?php

namespace NAO\AppBundle\Repository;

/**
 * NaoAvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaoAvesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBird($term)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.lbNom LIKE :lbNom')
            ->setParameter('lbNom', '%'.$term.'%')
        ;
        $arrayAss = $qb->getQuery()->getArrayResult();

        $array = array();
        foreach($arrayAss as $data)
        {
            $array[] = $data['lbNom'];
        }

        return $array;
    }
}
