# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OBSERVER:    ROLE_OBSERVER
        ROLE_NATURALIST:  ROLE_NATURALIST
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/observations/mesObservations, role: [ROLE_OBSERVER, ROLE_NATURALIST, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/profil, role: [ROLE_OBSERVER, ROLE_NATURALIST, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/admin, role: [ROLE_NATURALIST, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/admin/gestion-des-utilisateurs, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }