services:
#    nao_app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  nao_app.validator.contains_bird:
    class: AppBundle\Validator\Constraints\ContainsBirdValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator }

  twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }